{
 "title": "Fuel Prices API",
 "tags": [ "fuel-prices-api" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Upstream API Latency (P50, P90, P99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le, path) (rate(fuel_prices_govuk_api_http_response_latency_seconds_bucket[$__rate_interval])))",
     "legendFormat": "P50 - {{path}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le, path) (rate(fuel_prices_govuk_api_http_response_latency_seconds_bucket[$__rate_interval])))",
     "legendFormat": "P90 - {{path}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le, path) (rate(fuel_prices_govuk_api_http_response_latency_seconds_bucket[$__rate_interval])))",
     "legendFormat": "P99 - {{path}}"
    }
   ]
  },
  {
   "title": "Upstream API Call Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status_code, path) (rate(fuel_prices_govuk_api_http_response_status_codes_total[$__rate_interval]))",
     "legendFormat": "{{path}} - Status: {{status_code}}"
    }
   ]
  },
  {
   "title": "Fetched Fuel Prices",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(fuel_prices_govuk_api_items_fetched_total{path=\"pfs/fuel-prices\"}[60m]))",
     "legendFormat": "Fuel Prices"
    }
   ]
  },
  {
   "title": "Fetched PFS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(fuel_prices_govuk_api_items_fetched_total{path=\"pfs\"}[6h]))",
     "legendFormat": "PFS"
    }
   ]
  },
  {
   "title": "API Server Requests (Gin)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (code, path) (rate(gin_http_requests_total[$__rate_interval]))",
     "legendFormat": "{{path}} - Status: {{code}}"
    }
   ]
  }
 ]
}