### Token request
POST https://www.fuel-finder.service.gov.uk/api/v1/oauth/generate_access_token
Content-Type: application/json

{
  "client_id": "{{CLIENT_ID}}",
  "client_secret": "{{CLIENT_SECRET}}"
}

### Token refresh
POST https://www.fuel-finder.service.gov.uk/api/v1/oauth/regenerate_access_token
Content-Type: application/json

{
  "client_id": "{{CLIENT_ID}}",
  "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJraW5kIjoicHVibGljIiwiY2xpZW50X2lkIjoiRFFlNjU3Zm9YdDNEOVRZRDNKUnRJRzI1Y3ZMSmtjZkUiLCJpbmZvX3JlY2lwaWVudF9pZCI6ImJmNWY5MjdmLTc3MDgtNDkxMC04Mjg4LWZhODBjNzMzOTFmMiIsInRva2VuX3VzZSI6InJlZnJlc2giLCJzdWIiOiJEUWU2NTdmb1h0M0Q5VFlEM0pSdElHMjVjdkxKa2NmRSIsImF1ZCI6Im9hdXRoIiwiaWF0IjoxNzcxMDYzMDE2LCJleHAiOjE3NzEyMzU4MTZ9.dCkzx8TtX_PBoY20VuNftttVR2V6tIZoe0TDKTFwwKI"
}

### Get fuel prices
GET https://www.fuel-finder.service.gov.uk/api/v1/pfs/fuel-prices?batch-number=1
Authorization: Bearer {{TOKEN}}

### Get PFS details
GET https://www.fuel-finder.service.gov.uk/api/v1/pfs?batch-number=15
Authorization: Bearer {{TOKEN}}