INSERT INTO petrol_filling_stations (
    node_id,
    mft_organisation_name,
    public_phone_number,
    trading_name,
    is_same_trading_and_brand_name,
    brand_name,
    temporary_closure,
    permanent_closure,
    permanent_closure_date,
    is_motorway_service_station,
    is_supermarket_service_station,
    address_line_1,
    address_line_2,
    city,
    country,
    county,
    postcode,
    latitude,
    longitude,
    opening_times_json,
    amenities_json,
    fuel_types_json,
    updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(node_id) DO UPDATE SET
    mft_organisation_name = EXCLUDED.mft_organisation_name,
    public_phone_number = EXCLUDED.public_phone_number,
    trading_name = EXCLUDED.trading_name,
    is_same_trading_and_brand_name = EXCLUDED.is_same_trading_and_brand_name,
    brand_name = EXCLUDED.brand_name,
    temporary_closure = EXCLUDED.temporary_closure,
    permanent_closure = EXCLUDED.permanent_closure,
    permanent_closure_date = EXCLUDED.permanent_closure_date,
    is_motorway_service_station = EXCLUDED.is_motorway_service_station,
    is_supermarket_service_station = EXCLUDED.is_supermarket_service_station,
    address_line_1 = EXCLUDED.address_line_1,
    address_line_2 = EXCLUDED.address_line_2,
    city = EXCLUDED.city,
    country = EXCLUDED.country,
    county = EXCLUDED.county,
    postcode = EXCLUDED.postcode,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    opening_times_json = EXCLUDED.opening_times_json,
    amenities_json = EXCLUDED.amenities_json,
    fuel_types_json = EXCLUDED.fuel_types_json,
    updated_at = CURRENT_TIMESTAMP;